version: '3'

services:
  database:
    container_name: mongodb
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  database-gui:
    container_name: mongo-express
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=ndsproject
      - ME_CONFIG_BASICAUTH_PASSWORD=ndsproject
    depends_on:
      - database

  cache:
    container_name: redis
    image: redis:alpine3.12
    depends_on:
      - database-gui

  cache-gui:
    container_name: p3x-redis-ui
    image: patrikx3/p3x-redis-ui:2020.10.350
    ports:
      - "8082:7843"
    volumes:
      - ./redis-settings:/settings
    depends_on:
      - cache

  bot:
    container_name: telegram-bot
    build: .
    command: npm run serve
    depends_on:
      - cache-gui
    restart: on-failure
